### ISSUE TITLE
Add .editorconfig?

### ISSUE THREAD

**Issue by nathanaeljones** [fsprojects/ProjectScaffold#184]
I'm a fan of [EditorConfig](http://editorconfig.org/), which, AFAIK, is the best way to ensure consistent whitespace in a project, particularly when you have multiple editors and platforms involved. 

Here's a sample, edit to taste:

```
[*]
end_of_line = lf
insert_final_newline = true

[*.cs]
indent_style = space
indent_size = 4
charset = utf-8

[*.{fs,fsx}]
indent_style = space
indent_size = 4
charset = utf-8


[*.{c,cpp,h,hpp}]
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
```

File can be located in the repository root as ".editorconfig", and will apply to all projects within.

**Comment by cdrnet** [comment]
We should not define `end_of_line` here since this is controlled by git and depends on the environment.

**Comment by bbenoist** [comment]
:+1: for EditorConfig support!

However, I would prefer keeping the things as simple as possible and only override properties when exception arises.

Also I only indent by 2 spaces on my projects (mostly proprietary) because it makes the code more concise while still being as readable as with 4 spaces. It helps in reducing the widths of code lines, thus enabling the use of zoom (for visually impaired persons) and vertically-splitted views.

Here is my most used config:

```ini
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
charset = utf-8
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

# https://stackoverflow.com/questions/14482253/
[*.ps1]
charset = utf-8-bom
```

@cdrnet I am not sure if its actually working but defining `end_of_line` might prevent Visual Studio from mixing line endings.There are numerous complains about this and a [uservoice issue](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4160768-save-text-files-with-the-newline-convention-presen) has been opened but MS did not answered it.

**Comment by cdrnet** [comment]
@bbenoist ignore my comment above, I've just realized this repo uses non-standard line ending behavior anyway (IIRC as a work around for symbol source indexing).

**Comment by dsyme** [comment]
@nathanaeljones Please send a PR for this?

**Comment by dsyme** [comment]
Closing - a PR would be most welcome but it's not worth tracking every suggestion about improving the scaffold - just send the PR if you want it :)
