### ISSUE TITLE
Add Default Code of Conduct

### ISSUE THREAD

**Issue by WilliamBerryiii** [fsprojects/ProjectScaffold#284]
I think we should add a default Code of Conduct to the scaffold to reinforce our dedication to positive and supportive community development. Perhaps this one (http://contributor-covenant.org/), which has been widely adopted?

**Comment by forki** [comment]
I think this is something the projects should decide for themselves.

**Comment by WilliamBerryiii** [comment]
Shouldn't that approach then equally apply to the default license file that is included?

**Comment by forki** [comment]
In some sense yes.

Am 25.01.2017 08:44 schrieb "Bill Berry" <notifications@github.com>:

**Comment by spencerwi** [comment]
Yeah, that's a good case for removing the default license file. If this were a Forge-like tool rather than a "clone-and-get-going" repo (with no automation of its own), I'd say "present a license-picker", but since this project could be a base for any number or variety of other projects, it's probably better to be unopinionated about what license is the "fallback".

**Comment by forki** [comment]
yes a license picker would be nice
