### ISSUE TITLE
Disussion: Relation/Advantage over dotnet sdk templates?

### ISSUE THREAD

**Issue by matthid** [fsprojects/ProjectScaffold#324]
### Description

- Is this repository still required?
- Should we provide a sdk template out of this repository?
- Should we point to some existing template?

**Comment by Krzysztof-Cieslak** [comment]
+1 for providing `dotnet new` template for this repo.

**Comment by sergey-tihon** [comment]
One more question is What is the relationship between this project and https://github.com/TheAngryByrd/MiniScaffold ? (there is a template for mini scaffold)

**Comment by jackfoxy** [comment]
On my fork I already have converted this project to sdk

**Comment by jackfoxy** [comment]
@sergey-tihon  no relation I am aware of. MiniScaffold appears to already be a dotnet cli template project.

**Comment by kblohm** [comment]
As you have closed the issue, does that mean there is no real interest in converting to a dotnet template?

**Comment by jackfoxy** [comment]
@kblohm  do you have anything to add to the discussion? or a template proposal or PR?

**Comment by kblohm** [comment]
I had a discussion with @matthid in https://github.com/fsharp/FAKE/pull/1989 about creating templates for FAKE and he pointed me to this issue. No i do not have a template proposal or a PR yet.
Is there any interest in converting this repo to a dotnet template or are you generally happy with the way it currently works? If that is the case, there is probably no use in converting, otherwise i might give it a try, thats why i am asking :).

**Comment by jackfoxy** [comment]
Personally, I'm happy with the status quo, but others seem interested in a template. I don't have a strong opinion.

**Comment by kblohm** [comment]
Fair enough, feel free to close again.
